services:
  foosball-fsharp-api:
    image: foosball-api:fsharp
    restart: on-failure
    build:
      context: .
      dockerfile: Foosball.FSharp.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:80
